"""
secp256k1 curve constants.

secp256k1 is the elliptic curve y^2 = x^3 + 7 over a prime field, used in
Bitcoin for public key cryptography and Schnorr signatures (BIP340). The curve
is defined by two key parameters: the field prime P and the curve order Q.
"""

# The prime order of the finite field F_p. All point coordinates are reduced
# modulo this value. This specific prime allows fast modular reduction because
# of its proximity to 2^256.
P: int = 2**256 - 2**32 - 977
FIELD_ORDER: int = P

# The order of the generator point G, i.e., the number of points in the cyclic
# subgroup generated by G. All scalar (private key) arithmetic is done modulo Q.
Q: int = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
CURVE_ORDER: int = Q

# The x-coordinate of the generator point G, a fixed base point on secp256k1
# from which all public keys are derived: public_key = private_key * G.
G_x: int = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798

# The y-coordinate of the generator point G (even y, per BIP340 convention).
G_y: int = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
