"""
The scalar field of secp256k1: integers modulo Q (the curve order).

In elliptic curve cryptography, there are two distinct fields:
- The *base field* F_p: where point coordinates live (mod P)
- The *scalar field* Z_Q: where private keys, nonces, and multipliers live (mod Q)

Every secret in FROST/BIP340 is a scalar: private keys, polynomial coefficients,
nonce values, signature components, Lagrange coefficients, and secret shares.
All arithmetic on these values must be reduced modulo Q to stay in the group.

This class makes the scalar field explicit. Instead of scattered `% Q` operations
on raw ints throughout the codebase, scalar arithmetic is encapsulated here.
A learner reads this class once and understands all scalar reduction in FROST.

Why Q and not P? Because scalar multiplication k·G requires k to be in Z_Q
(the number of points in the cyclic group generated by G). Reducing mod Q ensures
that k·G cycles correctly: Q·G = identity (the point at infinity).
"""

import secrets
from typing import Literal

from .constants import Q


class Scalar:
    """Element of Z_Q, the scalar field of secp256k1.

    All private keys, nonces, shares, and signature components are scalars.
    Arithmetic is automatically reduced modulo Q (the curve order).

    This class makes the scalar field explicit: instead of scattered `% Q`
    operations on raw ints, scalar arithmetic is encapsulated here. A learner
    reads this class once and understands all scalar reduction in the codebase.

    Key operations: addition, subtraction, multiplication, negation, and
    modular inverse, all reduced mod Q. Scalar·Point multiplication is
    handled by Point.__rmul__.
    """

    def __init__(self, value: int):
        if not isinstance(value, int):
            raise TypeError("Scalar must be initialized from an integer.")
        self._value = value % Q

    @property
    def value(self) -> int:
        return self._value

    def __int__(self) -> int:
        return self._value

    def __add__(self, other: object) -> "Scalar":
        if not isinstance(other, Scalar):
            return NotImplemented
        return Scalar((self._value + other._value) % Q)

    def __sub__(self, other: object) -> "Scalar":
        if not isinstance(other, Scalar):
            return NotImplemented
        return Scalar((self._value - other._value) % Q)

    def __mul__(self, other: object) -> "Scalar":
        if not isinstance(other, Scalar):
            # Return NotImplemented so Point.__rmul__ can handle Scalar * Point
            return NotImplemented
        return Scalar((self._value * other._value) % Q)

    def __neg__(self) -> "Scalar":
        return Scalar((-self._value) % Q)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, Scalar):
            return self._value == other._value
        if isinstance(other, int):
            return self._value == other % Q
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._value)

    def __bool__(self) -> bool:
        return self._value != 0

    def __repr__(self) -> str:
        return f"Scalar({self._value})"

    def inv(self) -> "Scalar":
        """Modular inverse via Fermat's little theorem: a^(Q-2) = a^(-1) (mod Q).

        Raises ValueError if self is zero (zero has no inverse).
        """
        if self._value == 0:
            raise ValueError("Cannot invert zero.")
        return Scalar(pow(self._value, Q - 2, Q))

    def to_bytes(self, length: int = 32, byteorder: Literal["little", "big"] = "big") -> bytes:
        return self._value.to_bytes(length, byteorder)

    @classmethod
    def random(cls) -> "Scalar":
        """Generate a cryptographically random scalar in [0, Q-1]."""
        return cls(secrets.randbits(256))
